services:
  
#  preqin.frontend:
#    image: preqin.frontend
#    build:
#      context: .
#      dockerfile: frontend/Dockerfile
#    depends_on:
#      - preqin.investorsapi
#    ports:
#      - "5173:5173"
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://preqin.investorsapi:8080 || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  
  preqin.investorsapi:
    image: preqin.investorsapi
    build:
      context: .
      dockerfile: Preqin.InvestorsApi/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=investors;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
      - "8081:8081"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=investors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  pgdata: